#!/bin/bash
G1=0
while (( G1 < 720896 ))
do
	G2=0
	while (( G2 < 720896 ))
	do
		G3=0
		while (( G3 < 720896 ))
		do
			G4=0
			while (( G4 < 720896 ))
			do
				G5=0
				while (( G5 < 720896 ))
				do
					G6=0
					while (( G6 < 720896 ))
					do
						G7=0
						while (( G7 < 720896 ))
						do
							G8=0
							while (( G8 < 720896 ))
							do
								printf "%06d-%06d-%06d-%06d-%06d-%06d-%06d-%06d\n" $G1 $G2 $G3 $G4 $G5 $G6 $G7 $G8
								G8=$((G8+11))
							done
							G7=$((G7+11))
						done
						G6=$((G6+11))
					done
					G5=$((G5+11))
				done
				G4=$((G4+11))
			done
			G3=$((G3+11))
		done
		G2=$((G2+11))
	done
	G1=$((G1+11))
done
